kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-local-pv1
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain     # 回收策略：Retain（不清理）、Recycle（only nfs&hostpath）、Delete
  storageClassName: local-storage
  local:
    path: /opt/data/zookeeper
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node-1     # 在master上设置存储，或者通过节点的hostname设置为集群中任一节点
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-local-pv2
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain     # 回收策略：Retain（不清理）、Recycle（only nfs&hostpath）、Delete
  storageClassName: local-storage
  local:
    path: /opt/data/zookeeper
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node-2     # 在master上设置存储，或者通过节点的hostname设置为集群中任一节点
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-local-pv3
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain     # 回收策略：Retain（不清理）、Recycle（only nfs&hostpath）、Delete
  storageClassName: local-storage
  local:
    path: /opt/data/zookeeper
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node-3     # 在master上设置存储，或者通过节点的hostname设置为集群中任一节点
