apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-zk1
    labels:
      type: local
spec:
    capacity:
      storage: 2Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: "/opt/data/zookeeper"             #挂载的本地目录
    persistentVolumeReclaimPolicy: Recycle
    storageClassName: zk-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-zk2
    annotations:
    labels:
      type: local
spec:
    capacity:
      storage: 2Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: "/opt/data/zookeeper"              #挂载的本地目录
    persistentVolumeReclaimPolicy: Recycle
    storageClassName: zk-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-zk3
    annotations:
    labels:
      type: local
spec:
    capacity:
      storage: 2Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: "/opt/data/zookeeper"
    persistentVolumeReclaimPolicy: Recycle
    storageClassName: zk-pv
